# Generated by Django 5.0.3 on 2024-03-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehiclecolor_vehiclecondition_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_year',
            field=models.IntegerField(verbose_name='Ano da compra'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='Ano do modelo'),
        ),
        migrations.AlterField(
            model_name='vehiclebrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Marca do veículo'),
        ),
        migrations.AlterField(
            model_name='vehiclecolor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehiclecondition',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Condição do veículo'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
