# Generated by Django 5.0.3 on 2024-03-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_purchase_year_alter_vehicle_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclecolor', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclecondition', verbose_name='Condição do veículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclemodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclebrand', verbose_name='Marca do veículo'),
        ),
    ]
